/* eslint-disable */
// Generated by scripts/generate-prisma-shim.mjs

export const modelSchema = {
  "User": {
    "table": "User",
    "fields": {
      "id": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": false
      },
      "name": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": true
      },
      "email": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": true
      },
      "emailVerified": {
        "kind": "scalar",
        "type": "DateTime",
        "isList": false,
        "isOptional": true
      },
      "image": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": true
      },
      "createdAt": {
        "kind": "scalar",
        "type": "DateTime",
        "isList": false,
        "isOptional": false
      },
      "updatedAt": {
        "kind": "scalar",
        "type": "DateTime",
        "isList": false,
        "isOptional": false
      },
      "accounts": {
        "kind": "relation",
        "type": "Account",
        "isList": true,
        "isOptional": false
      },
      "sessions": {
        "kind": "relation",
        "type": "Session",
        "isList": true,
        "isOptional": false
      },
      "memberships": {
        "kind": "relation",
        "type": "OrganizationMembership",
        "isList": true,
        "isOptional": false
      },
      "campaignMemberships": {
        "kind": "relation",
        "type": "CampaignMembership",
        "isList": true,
        "isOptional": false
      },
      "ownedCampaigns": {
        "kind": "relation",
        "type": "Campaign",
        "isList": true,
        "isOptional": false
      },
      "organizationInvitationsSent": {
        "kind": "relation",
        "type": "OrganizationInvitation",
        "isList": true,
        "isOptional": false
      },
      "campaignInvitationsSent": {
        "kind": "relation",
        "type": "CampaignInvitation",
        "isList": true,
        "isOptional": false
      },
      "notesAuthored": {
        "kind": "relation",
        "type": "Note",
        "isList": true,
        "isOptional": false
      },
      "activities": {
        "kind": "relation",
        "type": "Activity",
        "isList": true,
        "isOptional": false
      },
      "syncJobs": {
        "kind": "relation",
        "type": "ExternalSyncJob",
        "isList": true,
        "isOptional": false
      },
      "videoReviews": {
        "kind": "relation",
        "type": "VideoReview",
        "isList": true,
        "isOptional": false
      }
    },
    "relations": {
      "accounts": {
        "model": "Account",
        "isList": true,
        "localFields": [
          "id"
        ],
        "remoteFields": [
          "userId"
        ]
      },
      "sessions": {
        "model": "Session",
        "isList": true,
        "localFields": [
          "id"
        ],
        "remoteFields": [
          "userId"
        ]
      },
      "memberships": {
        "model": "OrganizationMembership",
        "isList": true,
        "localFields": [
          "id"
        ],
        "remoteFields": [
          "userId"
        ]
      },
      "organizationInvitationsSent": {
        "model": "OrganizationInvitation",
        "isList": true,
        "localFields": [
          "id"
        ],
        "remoteFields": [
          "invitedByUserId"
        ]
      },
      "ownedCampaigns": {
        "model": "Campaign",
        "isList": true,
        "localFields": [
          "id"
        ],
        "remoteFields": [
          "ownerUserId"
        ]
      },
      "campaignMemberships": {
        "model": "CampaignMembership",
        "isList": true,
        "localFields": [
          "id"
        ],
        "remoteFields": [
          "userId"
        ]
      },
      "campaignInvitationsSent": {
        "model": "CampaignInvitation",
        "isList": true,
        "localFields": [
          "id"
        ],
        "remoteFields": [
          "invitedByUserId"
        ]
      },
      "videoReviews": {
        "model": "VideoReview",
        "isList": true,
        "localFields": [
          "id"
        ],
        "remoteFields": [
          "reviewerUserId"
        ]
      },
      "notesAuthored": {
        "model": "Note",
        "isList": true,
        "localFields": [
          "id"
        ],
        "remoteFields": [
          "authorUserId"
        ]
      },
      "activities": {
        "model": "Activity",
        "isList": true,
        "localFields": [
          "id"
        ],
        "remoteFields": [
          "actorUserId"
        ]
      },
      "syncJobs": {
        "model": "ExternalSyncJob",
        "isList": true,
        "localFields": [
          "id"
        ],
        "remoteFields": [
          "initiatedByUserId"
        ]
      }
    }
  },
  "Account": {
    "table": "Account",
    "fields": {
      "userId": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": false
      },
      "type": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": false
      },
      "provider": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": false
      },
      "providerAccountId": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": false
      },
      "refresh_token": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": true
      },
      "access_token": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": true
      },
      "expires_at": {
        "kind": "scalar",
        "type": "Int",
        "isList": false,
        "isOptional": true
      },
      "token_type": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": true
      },
      "scope": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": true
      },
      "id_token": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": true
      },
      "session_state": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": true
      },
      "createdAt": {
        "kind": "scalar",
        "type": "DateTime",
        "isList": false,
        "isOptional": false
      },
      "updatedAt": {
        "kind": "scalar",
        "type": "DateTime",
        "isList": false,
        "isOptional": false
      },
      "user": {
        "kind": "relation",
        "type": "User",
        "isList": false,
        "isOptional": false
      }
    },
    "relations": {
      "user": {
        "model": "User",
        "isList": false,
        "localFields": [
          "userId"
        ],
        "remoteFields": [
          "id"
        ]
      }
    }
  },
  "Session": {
    "table": "Session",
    "fields": {
      "sessionToken": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": false
      },
      "userId": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": false
      },
      "expires": {
        "kind": "scalar",
        "type": "DateTime",
        "isList": false,
        "isOptional": false
      },
      "createdAt": {
        "kind": "scalar",
        "type": "DateTime",
        "isList": false,
        "isOptional": false
      },
      "updatedAt": {
        "kind": "scalar",
        "type": "DateTime",
        "isList": false,
        "isOptional": false
      },
      "user": {
        "kind": "relation",
        "type": "User",
        "isList": false,
        "isOptional": false
      }
    },
    "relations": {
      "user": {
        "model": "User",
        "isList": false,
        "localFields": [
          "userId"
        ],
        "remoteFields": [
          "id"
        ]
      }
    }
  },
  "VerificationToken": {
    "table": "VerificationToken",
    "fields": {
      "identifier": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": false
      },
      "token": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": false
      },
      "expires": {
        "kind": "scalar",
        "type": "DateTime",
        "isList": false,
        "isOptional": false
      }
    },
    "relations": {}
  },
  "Organization": {
    "table": "Organization",
    "fields": {
      "id": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": false
      },
      "name": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": false
      },
      "slug": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": false
      },
      "createdById": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": true
      },
      "createdAt": {
        "kind": "scalar",
        "type": "DateTime",
        "isList": false,
        "isOptional": false
      },
      "updatedAt": {
        "kind": "scalar",
        "type": "DateTime",
        "isList": false,
        "isOptional": false
      },
      "memberships": {
        "kind": "relation",
        "type": "OrganizationMembership",
        "isList": true,
        "isOptional": false
      },
      "invitations": {
        "kind": "relation",
        "type": "OrganizationInvitation",
        "isList": true,
        "isOptional": false
      },
      "campaigns": {
        "kind": "relation",
        "type": "Campaign",
        "isList": true,
        "isOptional": false
      },
      "creators": {
        "kind": "relation",
        "type": "Creator",
        "isList": true,
        "isOptional": false
      },
      "tags": {
        "kind": "relation",
        "type": "Tag",
        "isList": true,
        "isOptional": false
      },
      "payouts": {
        "kind": "relation",
        "type": "Payout",
        "isList": true,
        "isOptional": false
      },
      "notes": {
        "kind": "relation",
        "type": "Note",
        "isList": true,
        "isOptional": false
      },
      "activities": {
        "kind": "relation",
        "type": "Activity",
        "isList": true,
        "isOptional": false
      },
      "syncJobs": {
        "kind": "relation",
        "type": "ExternalSyncJob",
        "isList": true,
        "isOptional": false
      },
      "sourceMaps": {
        "kind": "relation",
        "type": "SourceMapping",
        "isList": true,
        "isOptional": false
      },
      "twilioConfig": {
        "kind": "relation",
        "type": "OrganizationTwilioConfig",
        "isList": false,
        "isOptional": true
      },
      "tiktokAccounts": {
        "kind": "relation",
        "type": "OrganizationTikTokAccount",
        "isList": true,
        "isOptional": false
      },
      "messageThreads": {
        "kind": "relation",
        "type": "CreatorMessageThread",
        "isList": true,
        "isOptional": false
      },
      "sparkCodeRequests": {
        "kind": "relation",
        "type": "SparkCodeRequest",
        "isList": true,
        "isOptional": false
      },
      "messageEvents": {
        "kind": "relation",
        "type": "CreatorMessageEvent",
        "isList": true,
        "isOptional": false
      },
      "sparkAuthorizations": {
        "kind": "relation",
        "type": "SparkAuthorization",
        "isList": true,
        "isOptional": false
      },
      "creatorDeals": {
        "kind": "relation",
        "type": "CampaignCreatorDeal",
        "isList": true,
        "isOptional": false
      },
      "tiktokPaidMetricSnapshots": {
        "kind": "relation",
        "type": "TikTokPaidMetricSnapshot",
        "isList": true,
        "isOptional": false
      }
    },
    "relations": {
      "memberships": {
        "model": "OrganizationMembership",
        "isList": true,
        "localFields": [
          "id"
        ],
        "remoteFields": [
          "organizationId"
        ]
      },
      "invitations": {
        "model": "OrganizationInvitation",
        "isList": true,
        "localFields": [
          "id"
        ],
        "remoteFields": [
          "organizationId"
        ]
      },
      "campaigns": {
        "model": "Campaign",
        "isList": true,
        "localFields": [
          "id"
        ],
        "remoteFields": [
          "organizationId"
        ]
      },
      "creators": {
        "model": "Creator",
        "isList": true,
        "localFields": [
          "id"
        ],
        "remoteFields": [
          "organizationId"
        ]
      },
      "creatorDeals": {
        "model": "CampaignCreatorDeal",
        "isList": true,
        "localFields": [
          "id"
        ],
        "remoteFields": [
          "organizationId"
        ]
      },
      "twilioConfig": {
        "model": "OrganizationTwilioConfig",
        "isList": false,
        "localFields": [
          "id"
        ],
        "remoteFields": [
          "organizationId"
        ]
      },
      "tiktokAccounts": {
        "model": "OrganizationTikTokAccount",
        "isList": true,
        "localFields": [
          "id"
        ],
        "remoteFields": [
          "organizationId"
        ]
      },
      "sparkCodeRequests": {
        "model": "SparkCodeRequest",
        "isList": true,
        "localFields": [
          "id"
        ],
        "remoteFields": [
          "organizationId"
        ]
      },
      "messageThreads": {
        "model": "CreatorMessageThread",
        "isList": true,
        "localFields": [
          "id"
        ],
        "remoteFields": [
          "organizationId"
        ]
      },
      "messageEvents": {
        "model": "CreatorMessageEvent",
        "isList": true,
        "localFields": [
          "id"
        ],
        "remoteFields": [
          "organizationId"
        ]
      },
      "sparkAuthorizations": {
        "model": "SparkAuthorization",
        "isList": true,
        "localFields": [
          "id"
        ],
        "remoteFields": [
          "organizationId"
        ]
      },
      "tiktokPaidMetricSnapshots": {
        "model": "TikTokPaidMetricSnapshot",
        "isList": true,
        "localFields": [
          "id"
        ],
        "remoteFields": [
          "organizationId"
        ]
      },
      "notes": {
        "model": "Note",
        "isList": true,
        "localFields": [
          "id"
        ],
        "remoteFields": [
          "organizationId"
        ]
      },
      "tags": {
        "model": "Tag",
        "isList": true,
        "localFields": [
          "id"
        ],
        "remoteFields": [
          "organizationId"
        ]
      },
      "payouts": {
        "model": "Payout",
        "isList": true,
        "localFields": [
          "id"
        ],
        "remoteFields": [
          "organizationId"
        ]
      },
      "activities": {
        "model": "Activity",
        "isList": true,
        "localFields": [
          "id"
        ],
        "remoteFields": [
          "organizationId"
        ]
      },
      "syncJobs": {
        "model": "ExternalSyncJob",
        "isList": true,
        "localFields": [
          "id"
        ],
        "remoteFields": [
          "organizationId"
        ]
      },
      "sourceMaps": {
        "model": "SourceMapping",
        "isList": true,
        "localFields": [
          "id"
        ],
        "remoteFields": [
          "organizationId"
        ]
      }
    }
  },
  "OrganizationMembership": {
    "table": "OrganizationMembership",
    "fields": {
      "id": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": false
      },
      "organizationId": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": false
      },
      "userId": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": false
      },
      "role": {
        "kind": "enum",
        "type": "OrganizationRole",
        "isList": false,
        "isOptional": false
      },
      "createdAt": {
        "kind": "scalar",
        "type": "DateTime",
        "isList": false,
        "isOptional": false
      },
      "updatedAt": {
        "kind": "scalar",
        "type": "DateTime",
        "isList": false,
        "isOptional": false
      },
      "organization": {
        "kind": "relation",
        "type": "Organization",
        "isList": false,
        "isOptional": false
      },
      "user": {
        "kind": "relation",
        "type": "User",
        "isList": false,
        "isOptional": false
      }
    },
    "relations": {
      "organization": {
        "model": "Organization",
        "isList": false,
        "localFields": [
          "organizationId"
        ],
        "remoteFields": [
          "id"
        ]
      },
      "user": {
        "model": "User",
        "isList": false,
        "localFields": [
          "userId"
        ],
        "remoteFields": [
          "id"
        ]
      }
    }
  },
  "OrganizationInvitation": {
    "table": "OrganizationInvitation",
    "fields": {
      "id": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": false
      },
      "organizationId": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": false
      },
      "email": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": false
      },
      "role": {
        "kind": "enum",
        "type": "OrganizationRole",
        "isList": false,
        "isOptional": false
      },
      "invitedByUserId": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": true
      },
      "acceptedAt": {
        "kind": "scalar",
        "type": "DateTime",
        "isList": false,
        "isOptional": true
      },
      "revokedAt": {
        "kind": "scalar",
        "type": "DateTime",
        "isList": false,
        "isOptional": true
      },
      "createdAt": {
        "kind": "scalar",
        "type": "DateTime",
        "isList": false,
        "isOptional": false
      },
      "updatedAt": {
        "kind": "scalar",
        "type": "DateTime",
        "isList": false,
        "isOptional": false
      },
      "organization": {
        "kind": "relation",
        "type": "Organization",
        "isList": false,
        "isOptional": false
      },
      "invitedBy": {
        "kind": "relation",
        "type": "User",
        "isList": false,
        "isOptional": true
      }
    },
    "relations": {
      "organization": {
        "model": "Organization",
        "isList": false,
        "localFields": [
          "organizationId"
        ],
        "remoteFields": [
          "id"
        ]
      },
      "invitedBy": {
        "model": "User",
        "isList": false,
        "localFields": [
          "invitedByUserId"
        ],
        "remoteFields": [
          "id"
        ]
      }
    }
  },
  "Campaign": {
    "table": "Campaign",
    "fields": {
      "id": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": false
      },
      "organizationId": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": false
      },
      "ownerUserId": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": true
      },
      "name": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": false
      },
      "createdAt": {
        "kind": "scalar",
        "type": "DateTime",
        "isList": false,
        "isOptional": false
      },
      "updatedAt": {
        "kind": "scalar",
        "type": "DateTime",
        "isList": false,
        "isOptional": false
      },
      "organization": {
        "kind": "relation",
        "type": "Organization",
        "isList": false,
        "isOptional": false
      },
      "owner": {
        "kind": "relation",
        "type": "User",
        "isList": false,
        "isOptional": true
      },
      "memberships": {
        "kind": "relation",
        "type": "CampaignMembership",
        "isList": true,
        "isOptional": false
      },
      "invitations": {
        "kind": "relation",
        "type": "CampaignInvitation",
        "isList": true,
        "isOptional": false
      },
      "creators": {
        "kind": "relation",
        "type": "CampaignCreator",
        "isList": true,
        "isOptional": false
      },
      "videos": {
        "kind": "relation",
        "type": "Video",
        "isList": true,
        "isOptional": false
      },
      "payouts": {
        "kind": "relation",
        "type": "Payout",
        "isList": true,
        "isOptional": false
      }
    },
    "relations": {
      "organization": {
        "model": "Organization",
        "isList": false,
        "localFields": [
          "organizationId"
        ],
        "remoteFields": [
          "id"
        ]
      },
      "owner": {
        "model": "User",
        "isList": false,
        "localFields": [
          "ownerUserId"
        ],
        "remoteFields": [
          "id"
        ]
      },
      "memberships": {
        "model": "CampaignMembership",
        "isList": true,
        "localFields": [
          "id"
        ],
        "remoteFields": [
          "campaignId"
        ]
      },
      "invitations": {
        "model": "CampaignInvitation",
        "isList": true,
        "localFields": [
          "id"
        ],
        "remoteFields": [
          "campaignId"
        ]
      },
      "creators": {
        "model": "CampaignCreator",
        "isList": true,
        "localFields": [
          "id"
        ],
        "remoteFields": [
          "campaignId"
        ]
      },
      "videos": {
        "model": "Video",
        "isList": true,
        "localFields": [
          "id"
        ],
        "remoteFields": [
          "campaignId"
        ]
      },
      "payouts": {
        "model": "Payout",
        "isList": true,
        "localFields": [
          "id"
        ],
        "remoteFields": [
          "campaignId"
        ]
      }
    }
  },
  "CampaignMembership": {
    "table": "CampaignMembership",
    "fields": {
      "id": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": false
      },
      "campaignId": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": false
      },
      "userId": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": false
      },
      "role": {
        "kind": "enum",
        "type": "CampaignRole",
        "isList": false,
        "isOptional": false
      },
      "createdAt": {
        "kind": "scalar",
        "type": "DateTime",
        "isList": false,
        "isOptional": false
      },
      "updatedAt": {
        "kind": "scalar",
        "type": "DateTime",
        "isList": false,
        "isOptional": false
      },
      "campaign": {
        "kind": "relation",
        "type": "Campaign",
        "isList": false,
        "isOptional": false
      },
      "user": {
        "kind": "relation",
        "type": "User",
        "isList": false,
        "isOptional": false
      }
    },
    "relations": {
      "campaign": {
        "model": "Campaign",
        "isList": false,
        "localFields": [
          "campaignId"
        ],
        "remoteFields": [
          "id"
        ]
      },
      "user": {
        "model": "User",
        "isList": false,
        "localFields": [
          "userId"
        ],
        "remoteFields": [
          "id"
        ]
      }
    }
  },
  "CampaignInvitation": {
    "table": "CampaignInvitation",
    "fields": {
      "id": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": false
      },
      "campaignId": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": false
      },
      "email": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": false
      },
      "role": {
        "kind": "enum",
        "type": "CampaignRole",
        "isList": false,
        "isOptional": false
      },
      "invitedByUserId": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": true
      },
      "acceptedAt": {
        "kind": "scalar",
        "type": "DateTime",
        "isList": false,
        "isOptional": true
      },
      "revokedAt": {
        "kind": "scalar",
        "type": "DateTime",
        "isList": false,
        "isOptional": true
      },
      "createdAt": {
        "kind": "scalar",
        "type": "DateTime",
        "isList": false,
        "isOptional": false
      },
      "updatedAt": {
        "kind": "scalar",
        "type": "DateTime",
        "isList": false,
        "isOptional": false
      },
      "campaign": {
        "kind": "relation",
        "type": "Campaign",
        "isList": false,
        "isOptional": false
      },
      "invitedBy": {
        "kind": "relation",
        "type": "User",
        "isList": false,
        "isOptional": true
      }
    },
    "relations": {
      "campaign": {
        "model": "Campaign",
        "isList": false,
        "localFields": [
          "campaignId"
        ],
        "remoteFields": [
          "id"
        ]
      },
      "invitedBy": {
        "model": "User",
        "isList": false,
        "localFields": [
          "invitedByUserId"
        ],
        "remoteFields": [
          "id"
        ]
      }
    }
  },
  "Creator": {
    "table": "Creator",
    "fields": {
      "id": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": false
      },
      "organizationId": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": false
      },
      "displayName": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": false
      },
      "primaryNiche": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": true
      },
      "region": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": true
      },
      "language": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": true
      },
      "internalStatus": {
        "kind": "enum",
        "type": "CreatorStatus",
        "isList": false,
        "isOptional": false
      },
      "notesSummary": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": true
      },
      "contactEmail": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": true
      },
      "customTags": {
        "kind": "scalar",
        "type": "String",
        "isList": true,
        "isOptional": false
      },
      "createdAt": {
        "kind": "scalar",
        "type": "DateTime",
        "isList": false,
        "isOptional": false
      },
      "updatedAt": {
        "kind": "scalar",
        "type": "DateTime",
        "isList": false,
        "isOptional": false
      },
      "organization": {
        "kind": "relation",
        "type": "Organization",
        "isList": false,
        "isOptional": false
      },
      "platformAccounts": {
        "kind": "relation",
        "type": "CreatorPlatformAccount",
        "isList": true,
        "isOptional": false
      },
      "metricsSnapshots": {
        "kind": "relation",
        "type": "CreatorMetricsSnapshot",
        "isList": true,
        "isOptional": false
      },
      "campaignLinks": {
        "kind": "relation",
        "type": "CampaignCreator",
        "isList": true,
        "isOptional": false
      },
      "videos": {
        "kind": "relation",
        "type": "Video",
        "isList": true,
        "isOptional": false
      },
      "creatorTags": {
        "kind": "relation",
        "type": "CreatorTag",
        "isList": true,
        "isOptional": false
      },
      "payouts": {
        "kind": "relation",
        "type": "Payout",
        "isList": true,
        "isOptional": false
      },
      "contactPoints": {
        "kind": "relation",
        "type": "CreatorContactPoint",
        "isList": true,
        "isOptional": false
      },
      "messageThreads": {
        "kind": "relation",
        "type": "CreatorMessageThread",
        "isList": true,
        "isOptional": false
      },
      "sparkCodeRequests": {
        "kind": "relation",
        "type": "SparkCodeRequest",
        "isList": true,
        "isOptional": false
      },
      "messageEvents": {
        "kind": "relation",
        "type": "CreatorMessageEvent",
        "isList": true,
        "isOptional": false
      },
      "sparkAuthorizations": {
        "kind": "relation",
        "type": "SparkAuthorization",
        "isList": true,
        "isOptional": false
      },
      "tiktokPaidMetricSnapshots": {
        "kind": "relation",
        "type": "TikTokPaidMetricSnapshot",
        "isList": true,
        "isOptional": false
      }
    },
    "relations": {
      "organization": {
        "model": "Organization",
        "isList": false,
        "localFields": [
          "organizationId"
        ],
        "remoteFields": [
          "id"
        ]
      },
      "platformAccounts": {
        "model": "CreatorPlatformAccount",
        "isList": true,
        "localFields": [
          "id"
        ],
        "remoteFields": [
          "creatorId"
        ]
      },
      "metricsSnapshots": {
        "model": "CreatorMetricsSnapshot",
        "isList": true,
        "localFields": [
          "id"
        ],
        "remoteFields": [
          "creatorId"
        ]
      },
      "campaignLinks": {
        "model": "CampaignCreator",
        "isList": true,
        "localFields": [
          "id"
        ],
        "remoteFields": [
          "creatorId"
        ]
      },
      "videos": {
        "model": "Video",
        "isList": true,
        "localFields": [
          "id"
        ],
        "remoteFields": [
          "creatorId"
        ]
      },
      "contactPoints": {
        "model": "CreatorContactPoint",
        "isList": true,
        "localFields": [
          "id"
        ],
        "remoteFields": [
          "creatorId"
        ]
      },
      "sparkCodeRequests": {
        "model": "SparkCodeRequest",
        "isList": true,
        "localFields": [
          "id"
        ],
        "remoteFields": [
          "creatorId"
        ]
      },
      "messageThreads": {
        "model": "CreatorMessageThread",
        "isList": true,
        "localFields": [
          "id"
        ],
        "remoteFields": [
          "creatorId"
        ]
      },
      "messageEvents": {
        "model": "CreatorMessageEvent",
        "isList": true,
        "localFields": [
          "id"
        ],
        "remoteFields": [
          "creatorId"
        ]
      },
      "sparkAuthorizations": {
        "model": "SparkAuthorization",
        "isList": true,
        "localFields": [
          "id"
        ],
        "remoteFields": [
          "creatorId"
        ]
      },
      "tiktokPaidMetricSnapshots": {
        "model": "TikTokPaidMetricSnapshot",
        "isList": true,
        "localFields": [
          "id"
        ],
        "remoteFields": [
          "creatorId"
        ]
      },
      "creatorTags": {
        "model": "CreatorTag",
        "isList": true,
        "localFields": [
          "id"
        ],
        "remoteFields": [
          "creatorId"
        ]
      },
      "payouts": {
        "model": "Payout",
        "isList": true,
        "localFields": [
          "id"
        ],
        "remoteFields": [
          "creatorId"
        ]
      }
    }
  },
  "CreatorPlatformAccount": {
    "table": "CreatorPlatformAccount",
    "fields": {
      "id": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": false
      },
      "creatorId": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": false
      },
      "platform": {
        "kind": "enum",
        "type": "Platform",
        "isList": false,
        "isOptional": false
      },
      "sourceAccountId": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": true
      },
      "handle": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": false
      },
      "profileUrl": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": true
      },
      "followerCount": {
        "kind": "scalar",
        "type": "Int",
        "isList": false,
        "isOptional": true
      },
      "averageViews": {
        "kind": "scalar",
        "type": "Int",
        "isList": false,
        "isOptional": true
      },
      "averageEngagementRate": {
        "kind": "scalar",
        "type": "Float",
        "isList": false,
        "isOptional": true
      },
      "contactInfo": {
        "kind": "scalar",
        "type": "Json",
        "isList": false,
        "isOptional": true
      },
      "lastSyncedAt": {
        "kind": "scalar",
        "type": "DateTime",
        "isList": false,
        "isOptional": true
      },
      "rawPayload": {
        "kind": "scalar",
        "type": "Json",
        "isList": false,
        "isOptional": true
      },
      "createdAt": {
        "kind": "scalar",
        "type": "DateTime",
        "isList": false,
        "isOptional": false
      },
      "updatedAt": {
        "kind": "scalar",
        "type": "DateTime",
        "isList": false,
        "isOptional": false
      },
      "creator": {
        "kind": "relation",
        "type": "Creator",
        "isList": false,
        "isOptional": false
      },
      "metricsSnapshots": {
        "kind": "relation",
        "type": "CreatorMetricsSnapshot",
        "isList": true,
        "isOptional": false
      },
      "videos": {
        "kind": "relation",
        "type": "Video",
        "isList": true,
        "isOptional": false
      }
    },
    "relations": {
      "creator": {
        "model": "Creator",
        "isList": false,
        "localFields": [
          "creatorId"
        ],
        "remoteFields": [
          "id"
        ]
      },
      "metricsSnapshots": {
        "model": "CreatorMetricsSnapshot",
        "isList": true,
        "localFields": [
          "id"
        ],
        "remoteFields": [
          "platformAccountId"
        ]
      },
      "videos": {
        "model": "Video",
        "isList": true,
        "localFields": [
          "id"
        ],
        "remoteFields": [
          "creatorPlatformAccountId"
        ]
      }
    }
  },
  "CreatorMetricsSnapshot": {
    "table": "CreatorMetricsSnapshot",
    "fields": {
      "id": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": false
      },
      "creatorId": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": false
      },
      "platformAccountId": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": true
      },
      "capturedAt": {
        "kind": "scalar",
        "type": "DateTime",
        "isList": false,
        "isOptional": false
      },
      "followerCount": {
        "kind": "scalar",
        "type": "Int",
        "isList": false,
        "isOptional": true
      },
      "averageViews": {
        "kind": "scalar",
        "type": "Int",
        "isList": false,
        "isOptional": true
      },
      "averageEngagementRate": {
        "kind": "scalar",
        "type": "Float",
        "isList": false,
        "isOptional": true
      },
      "sourcePayload": {
        "kind": "scalar",
        "type": "Json",
        "isList": false,
        "isOptional": true
      },
      "creator": {
        "kind": "relation",
        "type": "Creator",
        "isList": false,
        "isOptional": false
      },
      "platformAccount": {
        "kind": "relation",
        "type": "CreatorPlatformAccount",
        "isList": false,
        "isOptional": true
      }
    },
    "relations": {
      "creator": {
        "model": "Creator",
        "isList": false,
        "localFields": [
          "creatorId"
        ],
        "remoteFields": [
          "id"
        ]
      },
      "platformAccount": {
        "model": "CreatorPlatformAccount",
        "isList": false,
        "localFields": [
          "platformAccountId"
        ],
        "remoteFields": [
          "id"
        ]
      }
    }
  },
  "CampaignCreator": {
    "table": "CampaignCreator",
    "fields": {
      "id": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": false
      },
      "campaignId": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": false
      },
      "creatorId": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": false
      },
      "outreachStatus": {
        "kind": "enum",
        "type": "OutreachStatus",
        "isList": false,
        "isOptional": false
      },
      "dealStatus": {
        "kind": "enum",
        "type": "DealStatus",
        "isList": false,
        "isOptional": false
      },
      "deliverableStatus": {
        "kind": "enum",
        "type": "DeliverableStatus",
        "isList": false,
        "isOptional": false
      },
      "approvalStatus": {
        "kind": "enum",
        "type": "ApprovalStatus",
        "isList": false,
        "isOptional": false
      },
      "postingStatus": {
        "kind": "enum",
        "type": "PostingStatus",
        "isList": false,
        "isOptional": false
      },
      "payoutStatus": {
        "kind": "enum",
        "type": "PayoutStatus",
        "isList": false,
        "isOptional": false
      },
      "agreedRate": {
        "kind": "scalar",
        "type": "Decimal",
        "isList": false,
        "isOptional": true
      },
      "dueDate": {
        "kind": "scalar",
        "type": "DateTime",
        "isList": false,
        "isOptional": true
      },
      "deliveredAt": {
        "kind": "scalar",
        "type": "DateTime",
        "isList": false,
        "isOptional": true
      },
      "postedAt": {
        "kind": "scalar",
        "type": "DateTime",
        "isList": false,
        "isOptional": true
      },
      "internalNotes": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": true
      },
      "createdAt": {
        "kind": "scalar",
        "type": "DateTime",
        "isList": false,
        "isOptional": false
      },
      "updatedAt": {
        "kind": "scalar",
        "type": "DateTime",
        "isList": false,
        "isOptional": false
      },
      "campaign": {
        "kind": "relation",
        "type": "Campaign",
        "isList": false,
        "isOptional": false
      },
      "creator": {
        "kind": "relation",
        "type": "Creator",
        "isList": false,
        "isOptional": false
      },
      "deal": {
        "kind": "relation",
        "type": "CampaignCreatorDeal",
        "isList": false,
        "isOptional": true
      },
      "payouts": {
        "kind": "relation",
        "type": "Payout",
        "isList": true,
        "isOptional": false
      }
    },
    "relations": {
      "campaign": {
        "model": "Campaign",
        "isList": false,
        "localFields": [
          "campaignId"
        ],
        "remoteFields": [
          "id"
        ]
      },
      "creator": {
        "model": "Creator",
        "isList": false,
        "localFields": [
          "creatorId"
        ],
        "remoteFields": [
          "id"
        ]
      },
      "deal": {
        "model": "CampaignCreatorDeal",
        "isList": false,
        "localFields": [
          "id"
        ],
        "remoteFields": [
          "campaignCreatorId"
        ]
      },
      "payouts": {
        "model": "Payout",
        "isList": true,
        "localFields": [
          "id"
        ],
        "remoteFields": [
          "campaignCreatorId"
        ]
      }
    }
  },
  "CampaignCreatorDeal": {
    "table": "CampaignCreatorDeal",
    "fields": {
      "id": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": false
      },
      "organizationId": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": false
      },
      "campaignCreatorId": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": false
      },
      "currency": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": false
      },
      "effectiveStartDate": {
        "kind": "scalar",
        "type": "DateTime",
        "isList": false,
        "isOptional": false
      },
      "effectiveEndDate": {
        "kind": "scalar",
        "type": "DateTime",
        "isList": false,
        "isOptional": true
      },
      "fixedFee": {
        "kind": "scalar",
        "type": "Decimal",
        "isList": false,
        "isOptional": true
      },
      "fixedFeeRecognitionDate": {
        "kind": "scalar",
        "type": "DateTime",
        "isList": false,
        "isOptional": true
      },
      "fixedFeePerVideo": {
        "kind": "scalar",
        "type": "Decimal",
        "isList": false,
        "isOptional": true
      },
      "cpmAmount": {
        "kind": "scalar",
        "type": "Decimal",
        "isList": false,
        "isOptional": true
      },
      "paidTrafficMetric": {
        "kind": "enum",
        "type": "CreatorDealPaidTrafficMetric",
        "isList": false,
        "isOptional": false
      },
      "deductPaidTraffic": {
        "kind": "scalar",
        "type": "Boolean",
        "isList": false,
        "isOptional": false
      },
      "viewCapPerVideo": {
        "kind": "scalar",
        "type": "Int",
        "isList": false,
        "isOptional": true
      },
      "viewWindowDays": {
        "kind": "scalar",
        "type": "Int",
        "isList": false,
        "isOptional": true
      },
      "payoutCapPerVideo": {
        "kind": "scalar",
        "type": "Decimal",
        "isList": false,
        "isOptional": true
      },
      "perVideoCapScope": {
        "kind": "enum",
        "type": "CreatorDealPerVideoCapScope",
        "isList": false,
        "isOptional": false
      },
      "payoutCapTotal": {
        "kind": "scalar",
        "type": "Decimal",
        "isList": false,
        "isOptional": true
      },
      "notes": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": true
      },
      "createdAt": {
        "kind": "scalar",
        "type": "DateTime",
        "isList": false,
        "isOptional": false
      },
      "updatedAt": {
        "kind": "scalar",
        "type": "DateTime",
        "isList": false,
        "isOptional": false
      },
      "organization": {
        "kind": "relation",
        "type": "Organization",
        "isList": false,
        "isOptional": false
      },
      "campaignCreator": {
        "kind": "relation",
        "type": "CampaignCreator",
        "isList": false,
        "isOptional": false
      }
    },
    "relations": {
      "organization": {
        "model": "Organization",
        "isList": false,
        "localFields": [
          "organizationId"
        ],
        "remoteFields": [
          "id"
        ]
      },
      "campaignCreator": {
        "model": "CampaignCreator",
        "isList": false,
        "localFields": [
          "campaignCreatorId"
        ],
        "remoteFields": [
          "id"
        ]
      }
    }
  },
  "Video": {
    "table": "Video",
    "fields": {
      "id": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": false
      },
      "creatorId": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": false
      },
      "creatorPlatformAccountId": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": true
      },
      "campaignId": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": true
      },
      "sourceVideoId": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": true
      },
      "platform": {
        "kind": "enum",
        "type": "Platform",
        "isList": false,
        "isOptional": false
      },
      "videoUrl": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": false
      },
      "titleOrCaption": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": true
      },
      "publishedAt": {
        "kind": "scalar",
        "type": "DateTime",
        "isList": false,
        "isOptional": true
      },
      "views": {
        "kind": "scalar",
        "type": "Int",
        "isList": false,
        "isOptional": true
      },
      "likes": {
        "kind": "scalar",
        "type": "Int",
        "isList": false,
        "isOptional": true
      },
      "comments": {
        "kind": "scalar",
        "type": "Int",
        "isList": false,
        "isOptional": true
      },
      "engagementRate": {
        "kind": "scalar",
        "type": "Float",
        "isList": false,
        "isOptional": true
      },
      "contentTags": {
        "kind": "scalar",
        "type": "String",
        "isList": true,
        "isOptional": false
      },
      "hookSummary": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": true
      },
      "rawPayload": {
        "kind": "scalar",
        "type": "Json",
        "isList": false,
        "isOptional": true
      },
      "lastSyncedAt": {
        "kind": "scalar",
        "type": "DateTime",
        "isList": false,
        "isOptional": true
      },
      "createdAt": {
        "kind": "scalar",
        "type": "DateTime",
        "isList": false,
        "isOptional": false
      },
      "updatedAt": {
        "kind": "scalar",
        "type": "DateTime",
        "isList": false,
        "isOptional": false
      },
      "creator": {
        "kind": "relation",
        "type": "Creator",
        "isList": false,
        "isOptional": false
      },
      "creatorPlatformAccount": {
        "kind": "relation",
        "type": "CreatorPlatformAccount",
        "isList": false,
        "isOptional": true
      },
      "campaign": {
        "kind": "relation",
        "type": "Campaign",
        "isList": false,
        "isOptional": true
      },
      "metricsSnapshots": {
        "kind": "relation",
        "type": "VideoMetricsSnapshot",
        "isList": true,
        "isOptional": false
      },
      "reviews": {
        "kind": "relation",
        "type": "VideoReview",
        "isList": true,
        "isOptional": false
      },
      "sparkCodeRequests": {
        "kind": "relation",
        "type": "SparkCodeRequest",
        "isList": true,
        "isOptional": false
      },
      "sparkAuthorizations": {
        "kind": "relation",
        "type": "SparkAuthorization",
        "isList": true,
        "isOptional": false
      },
      "tiktokPaidMetricSnapshots": {
        "kind": "relation",
        "type": "TikTokPaidMetricSnapshot",
        "isList": true,
        "isOptional": false
      }
    },
    "relations": {
      "creator": {
        "model": "Creator",
        "isList": false,
        "localFields": [
          "creatorId"
        ],
        "remoteFields": [
          "id"
        ]
      },
      "creatorPlatformAccount": {
        "model": "CreatorPlatformAccount",
        "isList": false,
        "localFields": [
          "creatorPlatformAccountId"
        ],
        "remoteFields": [
          "id"
        ]
      },
      "campaign": {
        "model": "Campaign",
        "isList": false,
        "localFields": [
          "campaignId"
        ],
        "remoteFields": [
          "id"
        ]
      },
      "reviews": {
        "model": "VideoReview",
        "isList": true,
        "localFields": [
          "id"
        ],
        "remoteFields": [
          "videoId"
        ]
      },
      "metricsSnapshots": {
        "model": "VideoMetricsSnapshot",
        "isList": true,
        "localFields": [
          "id"
        ],
        "remoteFields": [
          "videoId"
        ]
      },
      "sparkCodeRequests": {
        "model": "SparkCodeRequest",
        "isList": true,
        "localFields": [
          "id"
        ],
        "remoteFields": [
          "videoId"
        ]
      },
      "sparkAuthorizations": {
        "model": "SparkAuthorization",
        "isList": true,
        "localFields": [
          "id"
        ],
        "remoteFields": [
          "videoId"
        ]
      },
      "tiktokPaidMetricSnapshots": {
        "model": "TikTokPaidMetricSnapshot",
        "isList": true,
        "localFields": [
          "id"
        ],
        "remoteFields": [
          "videoId"
        ]
      }
    }
  },
  "VideoReview": {
    "table": "VideoReview",
    "fields": {
      "id": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": false
      },
      "videoId": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": false
      },
      "reviewerUserId": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": false
      },
      "reviewedAt": {
        "kind": "scalar",
        "type": "DateTime",
        "isList": false,
        "isOptional": false
      },
      "createdAt": {
        "kind": "scalar",
        "type": "DateTime",
        "isList": false,
        "isOptional": false
      },
      "updatedAt": {
        "kind": "scalar",
        "type": "DateTime",
        "isList": false,
        "isOptional": false
      },
      "video": {
        "kind": "relation",
        "type": "Video",
        "isList": false,
        "isOptional": false
      },
      "reviewer": {
        "kind": "relation",
        "type": "User",
        "isList": false,
        "isOptional": false
      }
    },
    "relations": {
      "video": {
        "model": "Video",
        "isList": false,
        "localFields": [
          "videoId"
        ],
        "remoteFields": [
          "id"
        ]
      },
      "reviewer": {
        "model": "User",
        "isList": false,
        "localFields": [
          "reviewerUserId"
        ],
        "remoteFields": [
          "id"
        ]
      }
    }
  },
  "VideoMetricsSnapshot": {
    "table": "VideoMetricsSnapshot",
    "fields": {
      "id": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": false
      },
      "videoId": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": false
      },
      "capturedAt": {
        "kind": "scalar",
        "type": "DateTime",
        "isList": false,
        "isOptional": false
      },
      "views": {
        "kind": "scalar",
        "type": "Int",
        "isList": false,
        "isOptional": true
      },
      "likes": {
        "kind": "scalar",
        "type": "Int",
        "isList": false,
        "isOptional": true
      },
      "comments": {
        "kind": "scalar",
        "type": "Int",
        "isList": false,
        "isOptional": true
      },
      "engagementRate": {
        "kind": "scalar",
        "type": "Float",
        "isList": false,
        "isOptional": true
      },
      "sourcePayload": {
        "kind": "scalar",
        "type": "Json",
        "isList": false,
        "isOptional": true
      },
      "video": {
        "kind": "relation",
        "type": "Video",
        "isList": false,
        "isOptional": false
      }
    },
    "relations": {
      "video": {
        "model": "Video",
        "isList": false,
        "localFields": [
          "videoId"
        ],
        "remoteFields": [
          "id"
        ]
      }
    }
  },
  "OrganizationTwilioConfig": {
    "table": "OrganizationTwilioConfig",
    "fields": {
      "id": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": false
      },
      "organizationId": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": false
      },
      "messagingServiceSid": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": true
      },
      "smsFrom": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": true
      },
      "whatsappFrom": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": true
      },
      "enabled": {
        "kind": "scalar",
        "type": "Boolean",
        "isList": false,
        "isOptional": false
      },
      "createdAt": {
        "kind": "scalar",
        "type": "DateTime",
        "isList": false,
        "isOptional": false
      },
      "updatedAt": {
        "kind": "scalar",
        "type": "DateTime",
        "isList": false,
        "isOptional": false
      },
      "organization": {
        "kind": "relation",
        "type": "Organization",
        "isList": false,
        "isOptional": false
      }
    },
    "relations": {
      "organization": {
        "model": "Organization",
        "isList": false,
        "localFields": [
          "organizationId"
        ],
        "remoteFields": [
          "id"
        ]
      }
    }
  },
  "OrganizationTikTokAccount": {
    "table": "OrganizationTikTokAccount",
    "fields": {
      "id": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": false
      },
      "organizationId": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": false
      },
      "advertiserId": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": false
      },
      "advertiserName": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": true
      },
      "accessToken": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": false
      },
      "refreshToken": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": true
      },
      "tokenType": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": true
      },
      "accessTokenExpiresAt": {
        "kind": "scalar",
        "type": "DateTime",
        "isList": false,
        "isOptional": true
      },
      "refreshTokenExpiresAt": {
        "kind": "scalar",
        "type": "DateTime",
        "isList": false,
        "isOptional": true
      },
      "scope": {
        "kind": "scalar",
        "type": "Json",
        "isList": false,
        "isOptional": true
      },
      "status": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": false
      },
      "lastValidatedAt": {
        "kind": "scalar",
        "type": "DateTime",
        "isList": false,
        "isOptional": true
      },
      "createdAt": {
        "kind": "scalar",
        "type": "DateTime",
        "isList": false,
        "isOptional": false
      },
      "updatedAt": {
        "kind": "scalar",
        "type": "DateTime",
        "isList": false,
        "isOptional": false
      },
      "organization": {
        "kind": "relation",
        "type": "Organization",
        "isList": false,
        "isOptional": false
      }
    },
    "relations": {
      "organization": {
        "model": "Organization",
        "isList": false,
        "localFields": [
          "organizationId"
        ],
        "remoteFields": [
          "id"
        ]
      }
    }
  },
  "CreatorContactPoint": {
    "table": "CreatorContactPoint",
    "fields": {
      "id": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": false
      },
      "creatorId": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": false
      },
      "channel": {
        "kind": "enum",
        "type": "MessagingChannel",
        "isList": false,
        "isOptional": false
      },
      "phoneE164": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": false
      },
      "isPrimary": {
        "kind": "scalar",
        "type": "Boolean",
        "isList": false,
        "isOptional": false
      },
      "verifiedAt": {
        "kind": "scalar",
        "type": "DateTime",
        "isList": false,
        "isOptional": true
      },
      "optInAt": {
        "kind": "scalar",
        "type": "DateTime",
        "isList": false,
        "isOptional": true
      },
      "optOutAt": {
        "kind": "scalar",
        "type": "DateTime",
        "isList": false,
        "isOptional": true
      },
      "createdAt": {
        "kind": "scalar",
        "type": "DateTime",
        "isList": false,
        "isOptional": false
      },
      "updatedAt": {
        "kind": "scalar",
        "type": "DateTime",
        "isList": false,
        "isOptional": false
      },
      "creator": {
        "kind": "relation",
        "type": "Creator",
        "isList": false,
        "isOptional": false
      },
      "threads": {
        "kind": "relation",
        "type": "CreatorMessageThread",
        "isList": true,
        "isOptional": false
      },
      "requests": {
        "kind": "relation",
        "type": "SparkCodeRequest",
        "isList": true,
        "isOptional": false
      },
      "messageEvents": {
        "kind": "relation",
        "type": "CreatorMessageEvent",
        "isList": true,
        "isOptional": false
      }
    },
    "relations": {
      "creator": {
        "model": "Creator",
        "isList": false,
        "localFields": [
          "creatorId"
        ],
        "remoteFields": [
          "id"
        ]
      },
      "requests": {
        "model": "SparkCodeRequest",
        "isList": true,
        "localFields": [
          "id"
        ],
        "remoteFields": [
          "contactPointId"
        ]
      },
      "threads": {
        "model": "CreatorMessageThread",
        "isList": true,
        "localFields": [
          "id"
        ],
        "remoteFields": [
          "contactPointId"
        ]
      },
      "messageEvents": {
        "model": "CreatorMessageEvent",
        "isList": true,
        "localFields": [
          "id"
        ],
        "remoteFields": [
          "contactPointId"
        ]
      }
    }
  },
  "SparkCodeRequest": {
    "table": "SparkCodeRequest",
    "fields": {
      "id": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": false
      },
      "organizationId": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": false
      },
      "creatorId": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": false
      },
      "videoId": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": true
      },
      "contactPointId": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": true
      },
      "threadId": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": true
      },
      "channel": {
        "kind": "enum",
        "type": "MessagingChannel",
        "isList": false,
        "isOptional": false
      },
      "requestToken": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": false
      },
      "status": {
        "kind": "enum",
        "type": "SparkCodeRequestStatus",
        "isList": false,
        "isOptional": false
      },
      "requestedAt": {
        "kind": "scalar",
        "type": "DateTime",
        "isList": false,
        "isOptional": false
      },
      "expiresAt": {
        "kind": "scalar",
        "type": "DateTime",
        "isList": false,
        "isOptional": true
      },
      "receivedAt": {
        "kind": "scalar",
        "type": "DateTime",
        "isList": false,
        "isOptional": true
      },
      "authorizedAt": {
        "kind": "scalar",
        "type": "DateTime",
        "isList": false,
        "isOptional": true
      },
      "failedAt": {
        "kind": "scalar",
        "type": "DateTime",
        "isList": false,
        "isOptional": true
      },
      "lastError": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": true
      },
      "createdAt": {
        "kind": "scalar",
        "type": "DateTime",
        "isList": false,
        "isOptional": false
      },
      "updatedAt": {
        "kind": "scalar",
        "type": "DateTime",
        "isList": false,
        "isOptional": false
      },
      "organization": {
        "kind": "relation",
        "type": "Organization",
        "isList": false,
        "isOptional": false
      },
      "creator": {
        "kind": "relation",
        "type": "Creator",
        "isList": false,
        "isOptional": false
      },
      "video": {
        "kind": "relation",
        "type": "Video",
        "isList": false,
        "isOptional": true
      },
      "contactPoint": {
        "kind": "relation",
        "type": "CreatorContactPoint",
        "isList": false,
        "isOptional": true
      },
      "thread": {
        "kind": "relation",
        "type": "CreatorMessageThread",
        "isList": false,
        "isOptional": true
      },
      "messageEvents": {
        "kind": "relation",
        "type": "CreatorMessageEvent",
        "isList": true,
        "isOptional": false
      },
      "authorizations": {
        "kind": "relation",
        "type": "SparkAuthorization",
        "isList": true,
        "isOptional": false
      }
    },
    "relations": {
      "organization": {
        "model": "Organization",
        "isList": false,
        "localFields": [
          "organizationId"
        ],
        "remoteFields": [
          "id"
        ]
      },
      "creator": {
        "model": "Creator",
        "isList": false,
        "localFields": [
          "creatorId"
        ],
        "remoteFields": [
          "id"
        ]
      },
      "video": {
        "model": "Video",
        "isList": false,
        "localFields": [
          "videoId"
        ],
        "remoteFields": [
          "id"
        ]
      },
      "contactPoint": {
        "model": "CreatorContactPoint",
        "isList": false,
        "localFields": [
          "contactPointId"
        ],
        "remoteFields": [
          "id"
        ]
      },
      "thread": {
        "model": "CreatorMessageThread",
        "isList": false,
        "localFields": [
          "threadId"
        ],
        "remoteFields": [
          "id"
        ]
      },
      "messageEvents": {
        "model": "CreatorMessageEvent",
        "isList": true,
        "localFields": [
          "id"
        ],
        "remoteFields": [
          "sparkCodeRequestId"
        ]
      },
      "authorizations": {
        "model": "SparkAuthorization",
        "isList": true,
        "localFields": [
          "id"
        ],
        "remoteFields": [
          "sparkCodeRequestId"
        ]
      }
    }
  },
  "CreatorMessageThread": {
    "table": "CreatorMessageThread",
    "fields": {
      "id": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": false
      },
      "organizationId": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": false
      },
      "creatorId": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": false
      },
      "contactPointId": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": true
      },
      "channel": {
        "kind": "enum",
        "type": "MessagingChannel",
        "isList": false,
        "isOptional": false
      },
      "state": {
        "kind": "enum",
        "type": "MessageThreadState",
        "isList": false,
        "isOptional": false
      },
      "lastInboundAt": {
        "kind": "scalar",
        "type": "DateTime",
        "isList": false,
        "isOptional": true
      },
      "lastOutboundAt": {
        "kind": "scalar",
        "type": "DateTime",
        "isList": false,
        "isOptional": true
      },
      "createdAt": {
        "kind": "scalar",
        "type": "DateTime",
        "isList": false,
        "isOptional": false
      },
      "updatedAt": {
        "kind": "scalar",
        "type": "DateTime",
        "isList": false,
        "isOptional": false
      },
      "organization": {
        "kind": "relation",
        "type": "Organization",
        "isList": false,
        "isOptional": false
      },
      "creator": {
        "kind": "relation",
        "type": "Creator",
        "isList": false,
        "isOptional": false
      },
      "contactPoint": {
        "kind": "relation",
        "type": "CreatorContactPoint",
        "isList": false,
        "isOptional": true
      },
      "requests": {
        "kind": "relation",
        "type": "SparkCodeRequest",
        "isList": true,
        "isOptional": false
      },
      "messageEvents": {
        "kind": "relation",
        "type": "CreatorMessageEvent",
        "isList": true,
        "isOptional": false
      }
    },
    "relations": {
      "organization": {
        "model": "Organization",
        "isList": false,
        "localFields": [
          "organizationId"
        ],
        "remoteFields": [
          "id"
        ]
      },
      "creator": {
        "model": "Creator",
        "isList": false,
        "localFields": [
          "creatorId"
        ],
        "remoteFields": [
          "id"
        ]
      },
      "contactPoint": {
        "model": "CreatorContactPoint",
        "isList": false,
        "localFields": [
          "contactPointId"
        ],
        "remoteFields": [
          "id"
        ]
      },
      "requests": {
        "model": "SparkCodeRequest",
        "isList": true,
        "localFields": [
          "id"
        ],
        "remoteFields": [
          "threadId"
        ]
      },
      "messageEvents": {
        "model": "CreatorMessageEvent",
        "isList": true,
        "localFields": [
          "id"
        ],
        "remoteFields": [
          "threadId"
        ]
      }
    }
  },
  "CreatorMessageEvent": {
    "table": "CreatorMessageEvent",
    "fields": {
      "id": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": false
      },
      "organizationId": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": false
      },
      "creatorId": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": true
      },
      "sparkCodeRequestId": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": true
      },
      "threadId": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": true
      },
      "contactPointId": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": true
      },
      "direction": {
        "kind": "enum",
        "type": "MessageDirection",
        "isList": false,
        "isOptional": false
      },
      "providerMessageSid": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": false
      },
      "channel": {
        "kind": "enum",
        "type": "MessagingChannel",
        "isList": false,
        "isOptional": false
      },
      "fromE164": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": false
      },
      "toE164": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": false
      },
      "body": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": false
      },
      "parseStatus": {
        "kind": "enum",
        "type": "MessageParseStatus",
        "isList": false,
        "isOptional": false
      },
      "parsedCodeHash": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": true
      },
      "deliveryStatus": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": true
      },
      "rawPayload": {
        "kind": "scalar",
        "type": "Json",
        "isList": false,
        "isOptional": true
      },
      "createdAt": {
        "kind": "scalar",
        "type": "DateTime",
        "isList": false,
        "isOptional": false
      },
      "updatedAt": {
        "kind": "scalar",
        "type": "DateTime",
        "isList": false,
        "isOptional": false
      },
      "organization": {
        "kind": "relation",
        "type": "Organization",
        "isList": false,
        "isOptional": false
      },
      "creator": {
        "kind": "relation",
        "type": "Creator",
        "isList": false,
        "isOptional": true
      },
      "sparkCodeRequest": {
        "kind": "relation",
        "type": "SparkCodeRequest",
        "isList": false,
        "isOptional": true
      },
      "thread": {
        "kind": "relation",
        "type": "CreatorMessageThread",
        "isList": false,
        "isOptional": true
      },
      "contactPoint": {
        "kind": "relation",
        "type": "CreatorContactPoint",
        "isList": false,
        "isOptional": true
      }
    },
    "relations": {
      "organization": {
        "model": "Organization",
        "isList": false,
        "localFields": [
          "organizationId"
        ],
        "remoteFields": [
          "id"
        ]
      },
      "creator": {
        "model": "Creator",
        "isList": false,
        "localFields": [
          "creatorId"
        ],
        "remoteFields": [
          "id"
        ]
      },
      "sparkCodeRequest": {
        "model": "SparkCodeRequest",
        "isList": false,
        "localFields": [
          "sparkCodeRequestId"
        ],
        "remoteFields": [
          "id"
        ]
      },
      "thread": {
        "model": "CreatorMessageThread",
        "isList": false,
        "localFields": [
          "threadId"
        ],
        "remoteFields": [
          "id"
        ]
      },
      "contactPoint": {
        "model": "CreatorContactPoint",
        "isList": false,
        "localFields": [
          "contactPointId"
        ],
        "remoteFields": [
          "id"
        ]
      }
    }
  },
  "SparkAuthorization": {
    "table": "SparkAuthorization",
    "fields": {
      "id": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": false
      },
      "organizationId": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": false
      },
      "creatorId": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": false
      },
      "videoId": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": true
      },
      "sparkCodeRequestId": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": true
      },
      "advertiserId": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": false
      },
      "authCodeHash": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": false
      },
      "identityType": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": true
      },
      "identityId": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": true
      },
      "identityAuthorizedBcId": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": true
      },
      "tiktokItemId": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": true
      },
      "authStartTime": {
        "kind": "scalar",
        "type": "DateTime",
        "isList": false,
        "isOptional": true
      },
      "authEndTime": {
        "kind": "scalar",
        "type": "DateTime",
        "isList": false,
        "isOptional": true
      },
      "status": {
        "kind": "enum",
        "type": "SparkAuthorizationStatus",
        "isList": false,
        "isOptional": false
      },
      "lastError": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": true
      },
      "createdAt": {
        "kind": "scalar",
        "type": "DateTime",
        "isList": false,
        "isOptional": false
      },
      "updatedAt": {
        "kind": "scalar",
        "type": "DateTime",
        "isList": false,
        "isOptional": false
      },
      "organization": {
        "kind": "relation",
        "type": "Organization",
        "isList": false,
        "isOptional": false
      },
      "creator": {
        "kind": "relation",
        "type": "Creator",
        "isList": false,
        "isOptional": false
      },
      "video": {
        "kind": "relation",
        "type": "Video",
        "isList": false,
        "isOptional": true
      },
      "sparkCodeRequest": {
        "kind": "relation",
        "type": "SparkCodeRequest",
        "isList": false,
        "isOptional": true
      }
    },
    "relations": {
      "organization": {
        "model": "Organization",
        "isList": false,
        "localFields": [
          "organizationId"
        ],
        "remoteFields": [
          "id"
        ]
      },
      "creator": {
        "model": "Creator",
        "isList": false,
        "localFields": [
          "creatorId"
        ],
        "remoteFields": [
          "id"
        ]
      },
      "video": {
        "model": "Video",
        "isList": false,
        "localFields": [
          "videoId"
        ],
        "remoteFields": [
          "id"
        ]
      },
      "sparkCodeRequest": {
        "model": "SparkCodeRequest",
        "isList": false,
        "localFields": [
          "sparkCodeRequestId"
        ],
        "remoteFields": [
          "id"
        ]
      }
    }
  },
  "TikTokPaidMetricSnapshot": {
    "table": "TikTokPaidMetricSnapshot",
    "fields": {
      "id": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": false
      },
      "organizationId": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": false
      },
      "creatorId": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": false
      },
      "videoId": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": true
      },
      "advertiserId": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": false
      },
      "tiktokItemId": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": true
      },
      "statDate": {
        "kind": "scalar",
        "type": "DateTime",
        "isList": false,
        "isOptional": true
      },
      "reportStartDate": {
        "kind": "scalar",
        "type": "DateTime",
        "isList": false,
        "isOptional": false
      },
      "reportEndDate": {
        "kind": "scalar",
        "type": "DateTime",
        "isList": false,
        "isOptional": false
      },
      "impressions": {
        "kind": "scalar",
        "type": "Int",
        "isList": false,
        "isOptional": true
      },
      "videoPlayActions": {
        "kind": "scalar",
        "type": "Int",
        "isList": false,
        "isOptional": true
      },
      "rawPayload": {
        "kind": "scalar",
        "type": "Json",
        "isList": false,
        "isOptional": true
      },
      "createdAt": {
        "kind": "scalar",
        "type": "DateTime",
        "isList": false,
        "isOptional": false
      },
      "updatedAt": {
        "kind": "scalar",
        "type": "DateTime",
        "isList": false,
        "isOptional": false
      },
      "organization": {
        "kind": "relation",
        "type": "Organization",
        "isList": false,
        "isOptional": false
      },
      "creator": {
        "kind": "relation",
        "type": "Creator",
        "isList": false,
        "isOptional": false
      },
      "video": {
        "kind": "relation",
        "type": "Video",
        "isList": false,
        "isOptional": true
      }
    },
    "relations": {
      "organization": {
        "model": "Organization",
        "isList": false,
        "localFields": [
          "organizationId"
        ],
        "remoteFields": [
          "id"
        ]
      },
      "creator": {
        "model": "Creator",
        "isList": false,
        "localFields": [
          "creatorId"
        ],
        "remoteFields": [
          "id"
        ]
      },
      "video": {
        "model": "Video",
        "isList": false,
        "localFields": [
          "videoId"
        ],
        "remoteFields": [
          "id"
        ]
      }
    }
  },
  "Note": {
    "table": "Note",
    "fields": {
      "id": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": false
      },
      "organizationId": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": false
      },
      "authorUserId": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": true
      },
      "entityType": {
        "kind": "enum",
        "type": "NoteEntityType",
        "isList": false,
        "isOptional": false
      },
      "entityId": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": false
      },
      "body": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": false
      },
      "metadata": {
        "kind": "scalar",
        "type": "Json",
        "isList": false,
        "isOptional": true
      },
      "createdAt": {
        "kind": "scalar",
        "type": "DateTime",
        "isList": false,
        "isOptional": false
      },
      "updatedAt": {
        "kind": "scalar",
        "type": "DateTime",
        "isList": false,
        "isOptional": false
      },
      "organization": {
        "kind": "relation",
        "type": "Organization",
        "isList": false,
        "isOptional": false
      },
      "author": {
        "kind": "relation",
        "type": "User",
        "isList": false,
        "isOptional": true
      }
    },
    "relations": {
      "organization": {
        "model": "Organization",
        "isList": false,
        "localFields": [
          "organizationId"
        ],
        "remoteFields": [
          "id"
        ]
      },
      "author": {
        "model": "User",
        "isList": false,
        "localFields": [
          "authorUserId"
        ],
        "remoteFields": [
          "id"
        ]
      }
    }
  },
  "Tag": {
    "table": "Tag",
    "fields": {
      "id": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": false
      },
      "organizationId": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": false
      },
      "name": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": false
      },
      "color": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": true
      },
      "createdAt": {
        "kind": "scalar",
        "type": "DateTime",
        "isList": false,
        "isOptional": false
      },
      "updatedAt": {
        "kind": "scalar",
        "type": "DateTime",
        "isList": false,
        "isOptional": false
      },
      "organization": {
        "kind": "relation",
        "type": "Organization",
        "isList": false,
        "isOptional": false
      },
      "creatorTags": {
        "kind": "relation",
        "type": "CreatorTag",
        "isList": true,
        "isOptional": false
      }
    },
    "relations": {
      "organization": {
        "model": "Organization",
        "isList": false,
        "localFields": [
          "organizationId"
        ],
        "remoteFields": [
          "id"
        ]
      },
      "creatorTags": {
        "model": "CreatorTag",
        "isList": true,
        "localFields": [
          "id"
        ],
        "remoteFields": [
          "tagId"
        ]
      }
    }
  },
  "CreatorTag": {
    "table": "CreatorTag",
    "fields": {
      "id": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": false
      },
      "creatorId": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": false
      },
      "tagId": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": false
      },
      "createdAt": {
        "kind": "scalar",
        "type": "DateTime",
        "isList": false,
        "isOptional": false
      },
      "creator": {
        "kind": "relation",
        "type": "Creator",
        "isList": false,
        "isOptional": false
      },
      "tag": {
        "kind": "relation",
        "type": "Tag",
        "isList": false,
        "isOptional": false
      }
    },
    "relations": {
      "creator": {
        "model": "Creator",
        "isList": false,
        "localFields": [
          "creatorId"
        ],
        "remoteFields": [
          "id"
        ]
      },
      "tag": {
        "model": "Tag",
        "isList": false,
        "localFields": [
          "tagId"
        ],
        "remoteFields": [
          "id"
        ]
      }
    }
  },
  "Payout": {
    "table": "Payout",
    "fields": {
      "id": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": false
      },
      "organizationId": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": false
      },
      "campaignId": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": true
      },
      "creatorId": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": true
      },
      "campaignCreatorId": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": true
      },
      "amount": {
        "kind": "scalar",
        "type": "Decimal",
        "isList": false,
        "isOptional": false
      },
      "currency": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": false
      },
      "status": {
        "kind": "enum",
        "type": "PayoutStatus",
        "isList": false,
        "isOptional": false
      },
      "payoutDate": {
        "kind": "scalar",
        "type": "DateTime",
        "isList": false,
        "isOptional": true
      },
      "paymentMethod": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": true
      },
      "externalReference": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": true
      },
      "createdAt": {
        "kind": "scalar",
        "type": "DateTime",
        "isList": false,
        "isOptional": false
      },
      "updatedAt": {
        "kind": "scalar",
        "type": "DateTime",
        "isList": false,
        "isOptional": false
      },
      "organization": {
        "kind": "relation",
        "type": "Organization",
        "isList": false,
        "isOptional": false
      },
      "campaign": {
        "kind": "relation",
        "type": "Campaign",
        "isList": false,
        "isOptional": true
      },
      "creator": {
        "kind": "relation",
        "type": "Creator",
        "isList": false,
        "isOptional": true
      },
      "campaignCreator": {
        "kind": "relation",
        "type": "CampaignCreator",
        "isList": false,
        "isOptional": true
      }
    },
    "relations": {
      "organization": {
        "model": "Organization",
        "isList": false,
        "localFields": [
          "organizationId"
        ],
        "remoteFields": [
          "id"
        ]
      },
      "campaign": {
        "model": "Campaign",
        "isList": false,
        "localFields": [
          "campaignId"
        ],
        "remoteFields": [
          "id"
        ]
      },
      "creator": {
        "model": "Creator",
        "isList": false,
        "localFields": [
          "creatorId"
        ],
        "remoteFields": [
          "id"
        ]
      },
      "campaignCreator": {
        "model": "CampaignCreator",
        "isList": false,
        "localFields": [
          "campaignCreatorId"
        ],
        "remoteFields": [
          "id"
        ]
      }
    }
  },
  "Activity": {
    "table": "Activity",
    "fields": {
      "id": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": false
      },
      "organizationId": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": false
      },
      "actorUserId": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": true
      },
      "entityType": {
        "kind": "enum",
        "type": "ActivityEntityType",
        "isList": false,
        "isOptional": false
      },
      "entityId": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": false
      },
      "action": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": false
      },
      "summary": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": true
      },
      "metadata": {
        "kind": "scalar",
        "type": "Json",
        "isList": false,
        "isOptional": true
      },
      "createdAt": {
        "kind": "scalar",
        "type": "DateTime",
        "isList": false,
        "isOptional": false
      },
      "organization": {
        "kind": "relation",
        "type": "Organization",
        "isList": false,
        "isOptional": false
      },
      "actor": {
        "kind": "relation",
        "type": "User",
        "isList": false,
        "isOptional": true
      }
    },
    "relations": {
      "organization": {
        "model": "Organization",
        "isList": false,
        "localFields": [
          "organizationId"
        ],
        "remoteFields": [
          "id"
        ]
      },
      "actor": {
        "model": "User",
        "isList": false,
        "localFields": [
          "actorUserId"
        ],
        "remoteFields": [
          "id"
        ]
      }
    }
  },
  "ExternalSyncJob": {
    "table": "ExternalSyncJob",
    "fields": {
      "id": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": false
      },
      "organizationId": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": false
      },
      "initiatedByUserId": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": true
      },
      "jobType": {
        "kind": "enum",
        "type": "SyncJobType",
        "isList": false,
        "isOptional": false
      },
      "status": {
        "kind": "enum",
        "type": "SyncJobStatus",
        "isList": false,
        "isOptional": false
      },
      "resourceType": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": false
      },
      "resourceId": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": true
      },
      "startedAt": {
        "kind": "scalar",
        "type": "DateTime",
        "isList": false,
        "isOptional": true
      },
      "finishedAt": {
        "kind": "scalar",
        "type": "DateTime",
        "isList": false,
        "isOptional": true
      },
      "errorMessage": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": true
      },
      "requestPayload": {
        "kind": "scalar",
        "type": "Json",
        "isList": false,
        "isOptional": true
      },
      "resultPayload": {
        "kind": "scalar",
        "type": "Json",
        "isList": false,
        "isOptional": true
      },
      "createdAt": {
        "kind": "scalar",
        "type": "DateTime",
        "isList": false,
        "isOptional": false
      },
      "updatedAt": {
        "kind": "scalar",
        "type": "DateTime",
        "isList": false,
        "isOptional": false
      },
      "organization": {
        "kind": "relation",
        "type": "Organization",
        "isList": false,
        "isOptional": false
      },
      "initiatedBy": {
        "kind": "relation",
        "type": "User",
        "isList": false,
        "isOptional": true
      }
    },
    "relations": {
      "organization": {
        "model": "Organization",
        "isList": false,
        "localFields": [
          "organizationId"
        ],
        "remoteFields": [
          "id"
        ]
      },
      "initiatedBy": {
        "model": "User",
        "isList": false,
        "localFields": [
          "initiatedByUserId"
        ],
        "remoteFields": [
          "id"
        ]
      }
    }
  },
  "SourceMapping": {
    "table": "SourceMapping",
    "fields": {
      "id": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": false
      },
      "organizationId": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": false
      },
      "localEntityType": {
        "kind": "enum",
        "type": "SourceEntityType",
        "isList": false,
        "isOptional": false
      },
      "localEntityId": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": false
      },
      "externalSource": {
        "kind": "enum",
        "type": "ExternalSource",
        "isList": false,
        "isOptional": false
      },
      "externalResourceType": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": false
      },
      "externalId": {
        "kind": "scalar",
        "type": "String",
        "isList": false,
        "isOptional": false
      },
      "lastSyncedAt": {
        "kind": "scalar",
        "type": "DateTime",
        "isList": false,
        "isOptional": true
      },
      "rawPayload": {
        "kind": "scalar",
        "type": "Json",
        "isList": false,
        "isOptional": true
      },
      "createdAt": {
        "kind": "scalar",
        "type": "DateTime",
        "isList": false,
        "isOptional": false
      },
      "updatedAt": {
        "kind": "scalar",
        "type": "DateTime",
        "isList": false,
        "isOptional": false
      },
      "organization": {
        "kind": "relation",
        "type": "Organization",
        "isList": false,
        "isOptional": false
      }
    },
    "relations": {
      "organization": {
        "model": "Organization",
        "isList": false,
        "localFields": [
          "organizationId"
        ],
        "remoteFields": [
          "id"
        ]
      }
    }
  }
} as const;

export type ModelSchema = typeof modelSchema;
export type ModelName = keyof ModelSchema;
