/* eslint-disable */
// Generated by scripts/generate-prisma-shim.mjs

export enum OrganizationRole {
  OWNER = "OWNER",
  ADMIN = "ADMIN",
  MEMBER = "MEMBER",
}

export enum CampaignRole {
  OWNER = "OWNER",
  MANAGER = "MANAGER",
  MEMBER = "MEMBER",
}

export enum Platform {
  TIKTOK = "TIKTOK",
  INSTAGRAM_REELS = "INSTAGRAM_REELS",
  YOUTUBE_SHORTS = "YOUTUBE_SHORTS",
}

export enum CreatorStatus {
  NEW = "NEW",
  QUALIFIED = "QUALIFIED",
  ACTIVE = "ACTIVE",
  INACTIVE = "INACTIVE",
  ARCHIVED = "ARCHIVED",
}

export enum OutreachStatus {
  NOT_STARTED = "NOT_STARTED",
  CONTACTED = "CONTACTED",
  RESPONDED = "RESPONDED",
  NO_RESPONSE = "NO_RESPONSE",
}

export enum DealStatus {
  LEAD = "LEAD",
  NEGOTIATING = "NEGOTIATING",
  AGREED = "AGREED",
  DECLINED = "DECLINED",
  CLOSED = "CLOSED",
}

export enum DeliverableStatus {
  NOT_BRIEFED = "NOT_BRIEFED",
  CONTENT_DUE = "CONTENT_DUE",
  CONTENT_RECEIVED = "CONTENT_RECEIVED",
  APPROVED = "APPROVED",
}

export enum ApprovalStatus {
  PENDING = "PENDING",
  APPROVED = "APPROVED",
  CHANGES_REQUESTED = "CHANGES_REQUESTED",
}

export enum PostingStatus {
  NOT_SCHEDULED = "NOT_SCHEDULED",
  READY_TO_POST = "READY_TO_POST",
  POSTED = "POSTED",
  ARCHIVED = "ARCHIVED",
}

export enum PayoutStatus {
  PENDING = "PENDING",
  APPROVED = "APPROVED",
  SCHEDULED = "SCHEDULED",
  PAID = "PAID",
  FAILED = "FAILED",
  CANCELLED = "CANCELLED",
}

export enum CreatorDealPaidTrafficMetric {
  VIDEO_PLAY_ACTIONS = "VIDEO_PLAY_ACTIONS",
  IMPRESSIONS = "IMPRESSIONS",
}

export enum CreatorDealPerVideoCapScope {
  CPM = "CPM",
  TOTAL = "TOTAL",
  NONE = "NONE",
}

export enum NoteEntityType {
  ORGANIZATION = "ORGANIZATION",
  CAMPAIGN = "CAMPAIGN",
  CREATOR = "CREATOR",
  VIDEO = "VIDEO",
  CAMPAIGN_CREATOR = "CAMPAIGN_CREATOR",
  PAYOUT = "PAYOUT",
}

export enum ActivityEntityType {
  ORGANIZATION = "ORGANIZATION",
  CAMPAIGN = "CAMPAIGN",
  CREATOR = "CREATOR",
  VIDEO = "VIDEO",
  CAMPAIGN_CREATOR = "CAMPAIGN_CREATOR",
  PAYOUT = "PAYOUT",
  SYNC_JOB = "SYNC_JOB",
}

export enum SyncJobType {
  ORGANIZATION_IMPORT = "ORGANIZATION_IMPORT",
  CREATOR_IMPORT = "CREATOR_IMPORT",
  CREATOR_REFRESH = "CREATOR_REFRESH",
  VIDEO_REFRESH = "VIDEO_REFRESH",
  CAMPAIGN_REFRESH = "CAMPAIGN_REFRESH",
}

export enum SyncJobStatus {
  QUEUED = "QUEUED",
  RUNNING = "RUNNING",
  SUCCEEDED = "SUCCEEDED",
  FAILED = "FAILED",
}

export enum ExternalSource {
  DATA_PROVIDER = "DATA_PROVIDER",
}

export enum SourceEntityType {
  CREATOR = "CREATOR",
  PLATFORM_ACCOUNT = "PLATFORM_ACCOUNT",
  VIDEO = "VIDEO",
  CAMPAIGN = "CAMPAIGN",
}

export enum MessagingChannel {
  SMS = "SMS",
  WHATSAPP = "WHATSAPP",
}

export enum MessageDirection {
  INBOUND = "INBOUND",
  OUTBOUND = "OUTBOUND",
}

export enum MessageParseStatus {
  NOT_ATTEMPTED = "NOT_ATTEMPTED",
  NO_CODE_FOUND = "NO_CODE_FOUND",
  CODE_FOUND = "CODE_FOUND",
  APPLIED = "APPLIED",
  FAILED = "FAILED",
}

export enum MessageThreadState {
  IDLE = "IDLE",
  AWAITING_SPARK_CODE = "AWAITING_SPARK_CODE",
  CODE_RECEIVED = "CODE_RECEIVED",
  AUTH_APPLIED = "AUTH_APPLIED",
  FAILED = "FAILED",
}

export enum SparkCodeRequestStatus {
  PENDING = "PENDING",
  RECEIVED = "RECEIVED",
  AUTHORIZED = "AUTHORIZED",
  FAILED = "FAILED",
  EXPIRED = "EXPIRED",
  CANCELLED = "CANCELLED",
}

export enum SparkAuthorizationStatus {
  PENDING = "PENDING",
  AUTHORIZED = "AUTHORIZED",
  FAILED = "FAILED",
  EXPIRED = "EXPIRED",
  REVOKED = "REVOKED",
}

export interface User {
  id: string;
  name: string | null;
  email: string | null;
  emailVerified: Date | null;
  image: string | null;
  createdAt: Date;
  updatedAt: Date;
}

export interface Account {
  userId: string;
  type: string;
  provider: string;
  providerAccountId: string;
  refresh_token: string | null;
  access_token: string | null;
  expires_at: number | null;
  token_type: string | null;
  scope: string | null;
  id_token: string | null;
  session_state: string | null;
  createdAt: Date;
  updatedAt: Date;
}

export interface Session {
  sessionToken: string;
  userId: string;
  expires: Date;
  createdAt: Date;
  updatedAt: Date;
}

export interface VerificationToken {
  identifier: string;
  token: string;
  expires: Date;
}

export interface Organization {
  id: string;
  name: string;
  slug: string;
  createdById: string | null;
  createdAt: Date;
  updatedAt: Date;
}

export interface OrganizationMembership {
  id: string;
  organizationId: string;
  userId: string;
  role: OrganizationRole;
  createdAt: Date;
  updatedAt: Date;
}

export interface OrganizationInvitation {
  id: string;
  organizationId: string;
  email: string;
  role: OrganizationRole;
  invitedByUserId: string | null;
  acceptedAt: Date | null;
  revokedAt: Date | null;
  createdAt: Date;
  updatedAt: Date;
}

export interface Campaign {
  id: string;
  organizationId: string;
  ownerUserId: string | null;
  name: string;
  createdAt: Date;
  updatedAt: Date;
}

export interface CampaignMembership {
  id: string;
  campaignId: string;
  userId: string;
  role: CampaignRole;
  createdAt: Date;
  updatedAt: Date;
}

export interface CampaignInvitation {
  id: string;
  campaignId: string;
  email: string;
  role: CampaignRole;
  invitedByUserId: string | null;
  acceptedAt: Date | null;
  revokedAt: Date | null;
  createdAt: Date;
  updatedAt: Date;
}

export interface Creator {
  id: string;
  organizationId: string;
  displayName: string;
  primaryNiche: string | null;
  region: string | null;
  language: string | null;
  internalStatus: CreatorStatus;
  notesSummary: string | null;
  contactEmail: string | null;
  customTags: string[];
  createdAt: Date;
  updatedAt: Date;
}

export interface CreatorPlatformAccount {
  id: string;
  creatorId: string;
  platform: Platform;
  sourceAccountId: string | null;
  handle: string;
  profileUrl: string | null;
  followerCount: number | null;
  averageViews: number | null;
  averageEngagementRate: number | null;
  contactInfo: Prisma.JsonValue | null | null;
  lastSyncedAt: Date | null;
  rawPayload: Prisma.JsonValue | null | null;
  createdAt: Date;
  updatedAt: Date;
}

export interface CreatorMetricsSnapshot {
  id: string;
  creatorId: string;
  platformAccountId: string | null;
  capturedAt: Date;
  followerCount: number | null;
  averageViews: number | null;
  averageEngagementRate: number | null;
  sourcePayload: Prisma.JsonValue | null | null;
}

export interface CampaignCreator {
  id: string;
  campaignId: string;
  creatorId: string;
  outreachStatus: OutreachStatus;
  dealStatus: DealStatus;
  deliverableStatus: DeliverableStatus;
  approvalStatus: ApprovalStatus;
  postingStatus: PostingStatus;
  payoutStatus: PayoutStatus;
  agreedRate: number | null;
  dueDate: Date | null;
  deliveredAt: Date | null;
  postedAt: Date | null;
  internalNotes: string | null;
  createdAt: Date;
  updatedAt: Date;
}

export interface CampaignCreatorDeal {
  id: string;
  organizationId: string;
  campaignCreatorId: string;
  currency: string;
  effectiveStartDate: Date;
  effectiveEndDate: Date | null;
  fixedFee: number | null;
  fixedFeeRecognitionDate: Date | null;
  fixedFeePerVideo: number | null;
  cpmAmount: number | null;
  paidTrafficMetric: CreatorDealPaidTrafficMetric;
  deductPaidTraffic: boolean;
  viewCapPerVideo: number | null;
  viewWindowDays: number | null;
  payoutCapPerVideo: number | null;
  perVideoCapScope: CreatorDealPerVideoCapScope;
  payoutCapTotal: number | null;
  notes: string | null;
  createdAt: Date;
  updatedAt: Date;
}

export interface Video {
  id: string;
  creatorId: string;
  creatorPlatformAccountId: string | null;
  campaignId: string | null;
  sourceVideoId: string | null;
  platform: Platform;
  videoUrl: string;
  titleOrCaption: string | null;
  publishedAt: Date | null;
  views: number | null;
  likes: number | null;
  comments: number | null;
  engagementRate: number | null;
  contentTags: string[];
  hookSummary: string | null;
  rawPayload: Prisma.JsonValue | null | null;
  lastSyncedAt: Date | null;
  createdAt: Date;
  updatedAt: Date;
}

export interface VideoReview {
  id: string;
  videoId: string;
  reviewerUserId: string;
  reviewedAt: Date;
  createdAt: Date;
  updatedAt: Date;
}

export interface VideoMetricsSnapshot {
  id: string;
  videoId: string;
  capturedAt: Date;
  views: number | null;
  likes: number | null;
  comments: number | null;
  engagementRate: number | null;
  sourcePayload: Prisma.JsonValue | null | null;
}

export interface OrganizationTwilioConfig {
  id: string;
  organizationId: string;
  messagingServiceSid: string | null;
  smsFrom: string | null;
  whatsappFrom: string | null;
  enabled: boolean;
  createdAt: Date;
  updatedAt: Date;
}

export interface OrganizationTikTokAccount {
  id: string;
  organizationId: string;
  advertiserId: string;
  advertiserName: string | null;
  accessToken: string;
  refreshToken: string | null;
  tokenType: string | null;
  accessTokenExpiresAt: Date | null;
  refreshTokenExpiresAt: Date | null;
  scope: Prisma.JsonValue | null | null;
  status: string;
  lastValidatedAt: Date | null;
  createdAt: Date;
  updatedAt: Date;
}

export interface CreatorContactPoint {
  id: string;
  creatorId: string;
  channel: MessagingChannel;
  phoneE164: string;
  isPrimary: boolean;
  verifiedAt: Date | null;
  optInAt: Date | null;
  optOutAt: Date | null;
  createdAt: Date;
  updatedAt: Date;
}

export interface SparkCodeRequest {
  id: string;
  organizationId: string;
  creatorId: string;
  videoId: string | null;
  contactPointId: string | null;
  threadId: string | null;
  channel: MessagingChannel;
  requestToken: string;
  status: SparkCodeRequestStatus;
  requestedAt: Date;
  expiresAt: Date | null;
  receivedAt: Date | null;
  authorizedAt: Date | null;
  failedAt: Date | null;
  lastError: string | null;
  createdAt: Date;
  updatedAt: Date;
}

export interface CreatorMessageThread {
  id: string;
  organizationId: string;
  creatorId: string;
  contactPointId: string | null;
  channel: MessagingChannel;
  state: MessageThreadState;
  lastInboundAt: Date | null;
  lastOutboundAt: Date | null;
  createdAt: Date;
  updatedAt: Date;
}

export interface CreatorMessageEvent {
  id: string;
  organizationId: string;
  creatorId: string | null;
  sparkCodeRequestId: string | null;
  threadId: string | null;
  contactPointId: string | null;
  direction: MessageDirection;
  providerMessageSid: string;
  channel: MessagingChannel;
  fromE164: string;
  toE164: string;
  body: string;
  parseStatus: MessageParseStatus;
  parsedCodeHash: string | null;
  deliveryStatus: string | null;
  rawPayload: Prisma.JsonValue | null | null;
  createdAt: Date;
  updatedAt: Date;
}

export interface SparkAuthorization {
  id: string;
  organizationId: string;
  creatorId: string;
  videoId: string | null;
  sparkCodeRequestId: string | null;
  advertiserId: string;
  authCodeHash: string;
  identityType: string | null;
  identityId: string | null;
  identityAuthorizedBcId: string | null;
  tiktokItemId: string | null;
  authStartTime: Date | null;
  authEndTime: Date | null;
  status: SparkAuthorizationStatus;
  lastError: string | null;
  createdAt: Date;
  updatedAt: Date;
}

export interface TikTokPaidMetricSnapshot {
  id: string;
  organizationId: string;
  creatorId: string;
  videoId: string | null;
  advertiserId: string;
  tiktokItemId: string | null;
  statDate: Date | null;
  reportStartDate: Date;
  reportEndDate: Date;
  impressions: number | null;
  videoPlayActions: number | null;
  rawPayload: Prisma.JsonValue | null | null;
  createdAt: Date;
  updatedAt: Date;
}

export interface TikTokAdPreviewUrl {
  id: string;
  organizationId: string;
  advertiserId: string;
  adId: string;
  adName: string | null;
  previewUrl: string;
  expiresAt: Date | null;
  importedAt: Date;
  sourceFileName: string | null;
  rawPayload: Prisma.JsonValue | null | null;
  createdAt: Date;
  updatedAt: Date;
}

export interface Note {
  id: string;
  organizationId: string;
  authorUserId: string | null;
  entityType: NoteEntityType;
  entityId: string;
  body: string;
  metadata: Prisma.JsonValue | null | null;
  createdAt: Date;
  updatedAt: Date;
}

export interface Tag {
  id: string;
  organizationId: string;
  name: string;
  color: string | null;
  createdAt: Date;
  updatedAt: Date;
}

export interface CreatorTag {
  id: string;
  creatorId: string;
  tagId: string;
  createdAt: Date;
}

export interface Payout {
  id: string;
  organizationId: string;
  campaignId: string | null;
  creatorId: string | null;
  campaignCreatorId: string | null;
  amount: number;
  currency: string;
  status: PayoutStatus;
  payoutDate: Date | null;
  paymentMethod: string | null;
  externalReference: string | null;
  createdAt: Date;
  updatedAt: Date;
}

export interface Activity {
  id: string;
  organizationId: string;
  actorUserId: string | null;
  entityType: ActivityEntityType;
  entityId: string;
  action: string;
  summary: string | null;
  metadata: Prisma.JsonValue | null | null;
  createdAt: Date;
}

export interface ExternalSyncJob {
  id: string;
  organizationId: string;
  initiatedByUserId: string | null;
  jobType: SyncJobType;
  status: SyncJobStatus;
  resourceType: string;
  resourceId: string | null;
  startedAt: Date | null;
  finishedAt: Date | null;
  errorMessage: string | null;
  requestPayload: Prisma.JsonValue | null | null;
  resultPayload: Prisma.JsonValue | null | null;
  createdAt: Date;
  updatedAt: Date;
}

export interface SourceMapping {
  id: string;
  organizationId: string;
  localEntityType: SourceEntityType;
  localEntityId: string;
  externalSource: ExternalSource;
  externalResourceType: string;
  externalId: string;
  lastSyncedAt: Date | null;
  rawPayload: Prisma.JsonValue | null | null;
  createdAt: Date;
  updatedAt: Date;
}

export namespace Prisma {
  export type JsonObject = { [key: string]: JsonValue };
  export type JsonArray = JsonValue[];
  export type JsonValue = string | number | boolean | null | JsonObject | JsonArray;
  export type InputJsonValue = JsonValue;
  export type InputJsonObject = JsonObject;
  export type SortOrder = "asc" | "desc";
  export type TransactionClient = any;
  export type GenericWhereInput = Record<string, unknown> & {
    AND?: GenericWhereInput[];
    OR?: GenericWhereInput[];
    NOT?: GenericWhereInput | GenericWhereInput[];
  };
  export type GenericOrderByInput = Record<string, unknown>;
  export type GenericSelect = Record<string, unknown>;
  export type GenericInput = Record<string, unknown>;
  export type UserWhereInput = GenericWhereInput;
  export type UserOrderByWithRelationInput = GenericOrderByInput;
  export type UserSelect = GenericSelect;
  export type UserCreateInput = GenericInput;
  export type UserUpdateInput = GenericInput;
  export type AccountWhereInput = GenericWhereInput;
  export type AccountOrderByWithRelationInput = GenericOrderByInput;
  export type AccountSelect = GenericSelect;
  export type AccountCreateInput = GenericInput;
  export type AccountUpdateInput = GenericInput;
  export type SessionWhereInput = GenericWhereInput;
  export type SessionOrderByWithRelationInput = GenericOrderByInput;
  export type SessionSelect = GenericSelect;
  export type SessionCreateInput = GenericInput;
  export type SessionUpdateInput = GenericInput;
  export type VerificationTokenWhereInput = GenericWhereInput;
  export type VerificationTokenOrderByWithRelationInput = GenericOrderByInput;
  export type VerificationTokenSelect = GenericSelect;
  export type VerificationTokenCreateInput = GenericInput;
  export type VerificationTokenUpdateInput = GenericInput;
  export type OrganizationWhereInput = GenericWhereInput;
  export type OrganizationOrderByWithRelationInput = GenericOrderByInput;
  export type OrganizationSelect = GenericSelect;
  export type OrganizationCreateInput = GenericInput;
  export type OrganizationUpdateInput = GenericInput;
  export type OrganizationMembershipWhereInput = GenericWhereInput;
  export type OrganizationMembershipOrderByWithRelationInput = GenericOrderByInput;
  export type OrganizationMembershipSelect = GenericSelect;
  export type OrganizationMembershipCreateInput = GenericInput;
  export type OrganizationMembershipUpdateInput = GenericInput;
  export type OrganizationInvitationWhereInput = GenericWhereInput;
  export type OrganizationInvitationOrderByWithRelationInput = GenericOrderByInput;
  export type OrganizationInvitationSelect = GenericSelect;
  export type OrganizationInvitationCreateInput = GenericInput;
  export type OrganizationInvitationUpdateInput = GenericInput;
  export type CampaignWhereInput = GenericWhereInput;
  export type CampaignOrderByWithRelationInput = GenericOrderByInput;
  export type CampaignSelect = GenericSelect;
  export type CampaignCreateInput = GenericInput;
  export type CampaignUpdateInput = GenericInput;
  export type CampaignMembershipWhereInput = GenericWhereInput;
  export type CampaignMembershipOrderByWithRelationInput = GenericOrderByInput;
  export type CampaignMembershipSelect = GenericSelect;
  export type CampaignMembershipCreateInput = GenericInput;
  export type CampaignMembershipUpdateInput = GenericInput;
  export type CampaignInvitationWhereInput = GenericWhereInput;
  export type CampaignInvitationOrderByWithRelationInput = GenericOrderByInput;
  export type CampaignInvitationSelect = GenericSelect;
  export type CampaignInvitationCreateInput = GenericInput;
  export type CampaignInvitationUpdateInput = GenericInput;
  export type CreatorWhereInput = GenericWhereInput;
  export type CreatorOrderByWithRelationInput = GenericOrderByInput;
  export type CreatorSelect = GenericSelect;
  export type CreatorCreateInput = GenericInput;
  export type CreatorUpdateInput = GenericInput;
  export type CreatorPlatformAccountWhereInput = GenericWhereInput;
  export type CreatorPlatformAccountOrderByWithRelationInput = GenericOrderByInput;
  export type CreatorPlatformAccountSelect = GenericSelect;
  export type CreatorPlatformAccountCreateInput = GenericInput;
  export type CreatorPlatformAccountUpdateInput = GenericInput;
  export type CreatorMetricsSnapshotWhereInput = GenericWhereInput;
  export type CreatorMetricsSnapshotOrderByWithRelationInput = GenericOrderByInput;
  export type CreatorMetricsSnapshotSelect = GenericSelect;
  export type CreatorMetricsSnapshotCreateInput = GenericInput;
  export type CreatorMetricsSnapshotUpdateInput = GenericInput;
  export type CampaignCreatorWhereInput = GenericWhereInput;
  export type CampaignCreatorOrderByWithRelationInput = GenericOrderByInput;
  export type CampaignCreatorSelect = GenericSelect;
  export type CampaignCreatorCreateInput = GenericInput;
  export type CampaignCreatorUpdateInput = GenericInput;
  export type CampaignCreatorDealWhereInput = GenericWhereInput;
  export type CampaignCreatorDealOrderByWithRelationInput = GenericOrderByInput;
  export type CampaignCreatorDealSelect = GenericSelect;
  export type CampaignCreatorDealCreateInput = GenericInput;
  export type CampaignCreatorDealUpdateInput = GenericInput;
  export type VideoWhereInput = GenericWhereInput;
  export type VideoOrderByWithRelationInput = GenericOrderByInput;
  export type VideoSelect = GenericSelect;
  export type VideoCreateInput = GenericInput;
  export type VideoUpdateInput = GenericInput;
  export type VideoReviewWhereInput = GenericWhereInput;
  export type VideoReviewOrderByWithRelationInput = GenericOrderByInput;
  export type VideoReviewSelect = GenericSelect;
  export type VideoReviewCreateInput = GenericInput;
  export type VideoReviewUpdateInput = GenericInput;
  export type VideoMetricsSnapshotWhereInput = GenericWhereInput;
  export type VideoMetricsSnapshotOrderByWithRelationInput = GenericOrderByInput;
  export type VideoMetricsSnapshotSelect = GenericSelect;
  export type VideoMetricsSnapshotCreateInput = GenericInput;
  export type VideoMetricsSnapshotUpdateInput = GenericInput;
  export type OrganizationTwilioConfigWhereInput = GenericWhereInput;
  export type OrganizationTwilioConfigOrderByWithRelationInput = GenericOrderByInput;
  export type OrganizationTwilioConfigSelect = GenericSelect;
  export type OrganizationTwilioConfigCreateInput = GenericInput;
  export type OrganizationTwilioConfigUpdateInput = GenericInput;
  export type OrganizationTikTokAccountWhereInput = GenericWhereInput;
  export type OrganizationTikTokAccountOrderByWithRelationInput = GenericOrderByInput;
  export type OrganizationTikTokAccountSelect = GenericSelect;
  export type OrganizationTikTokAccountCreateInput = GenericInput;
  export type OrganizationTikTokAccountUpdateInput = GenericInput;
  export type CreatorContactPointWhereInput = GenericWhereInput;
  export type CreatorContactPointOrderByWithRelationInput = GenericOrderByInput;
  export type CreatorContactPointSelect = GenericSelect;
  export type CreatorContactPointCreateInput = GenericInput;
  export type CreatorContactPointUpdateInput = GenericInput;
  export type SparkCodeRequestWhereInput = GenericWhereInput;
  export type SparkCodeRequestOrderByWithRelationInput = GenericOrderByInput;
  export type SparkCodeRequestSelect = GenericSelect;
  export type SparkCodeRequestCreateInput = GenericInput;
  export type SparkCodeRequestUpdateInput = GenericInput;
  export type CreatorMessageThreadWhereInput = GenericWhereInput;
  export type CreatorMessageThreadOrderByWithRelationInput = GenericOrderByInput;
  export type CreatorMessageThreadSelect = GenericSelect;
  export type CreatorMessageThreadCreateInput = GenericInput;
  export type CreatorMessageThreadUpdateInput = GenericInput;
  export type CreatorMessageEventWhereInput = GenericWhereInput;
  export type CreatorMessageEventOrderByWithRelationInput = GenericOrderByInput;
  export type CreatorMessageEventSelect = GenericSelect;
  export type CreatorMessageEventCreateInput = GenericInput;
  export type CreatorMessageEventUpdateInput = GenericInput;
  export type SparkAuthorizationWhereInput = GenericWhereInput;
  export type SparkAuthorizationOrderByWithRelationInput = GenericOrderByInput;
  export type SparkAuthorizationSelect = GenericSelect;
  export type SparkAuthorizationCreateInput = GenericInput;
  export type SparkAuthorizationUpdateInput = GenericInput;
  export type TikTokPaidMetricSnapshotWhereInput = GenericWhereInput;
  export type TikTokPaidMetricSnapshotOrderByWithRelationInput = GenericOrderByInput;
  export type TikTokPaidMetricSnapshotSelect = GenericSelect;
  export type TikTokPaidMetricSnapshotCreateInput = GenericInput;
  export type TikTokPaidMetricSnapshotUpdateInput = GenericInput;
  export type TikTokAdPreviewUrlWhereInput = GenericWhereInput;
  export type TikTokAdPreviewUrlOrderByWithRelationInput = GenericOrderByInput;
  export type TikTokAdPreviewUrlSelect = GenericSelect;
  export type TikTokAdPreviewUrlCreateInput = GenericInput;
  export type TikTokAdPreviewUrlUpdateInput = GenericInput;
  export type NoteWhereInput = GenericWhereInput;
  export type NoteOrderByWithRelationInput = GenericOrderByInput;
  export type NoteSelect = GenericSelect;
  export type NoteCreateInput = GenericInput;
  export type NoteUpdateInput = GenericInput;
  export type TagWhereInput = GenericWhereInput;
  export type TagOrderByWithRelationInput = GenericOrderByInput;
  export type TagSelect = GenericSelect;
  export type TagCreateInput = GenericInput;
  export type TagUpdateInput = GenericInput;
  export type CreatorTagWhereInput = GenericWhereInput;
  export type CreatorTagOrderByWithRelationInput = GenericOrderByInput;
  export type CreatorTagSelect = GenericSelect;
  export type CreatorTagCreateInput = GenericInput;
  export type CreatorTagUpdateInput = GenericInput;
  export type PayoutWhereInput = GenericWhereInput;
  export type PayoutOrderByWithRelationInput = GenericOrderByInput;
  export type PayoutSelect = GenericSelect;
  export type PayoutCreateInput = GenericInput;
  export type PayoutUpdateInput = GenericInput;
  export type ActivityWhereInput = GenericWhereInput;
  export type ActivityOrderByWithRelationInput = GenericOrderByInput;
  export type ActivitySelect = GenericSelect;
  export type ActivityCreateInput = GenericInput;
  export type ActivityUpdateInput = GenericInput;
  export type ExternalSyncJobWhereInput = GenericWhereInput;
  export type ExternalSyncJobOrderByWithRelationInput = GenericOrderByInput;
  export type ExternalSyncJobSelect = GenericSelect;
  export type ExternalSyncJobCreateInput = GenericInput;
  export type ExternalSyncJobUpdateInput = GenericInput;
  export type SourceMappingWhereInput = GenericWhereInput;
  export type SourceMappingOrderByWithRelationInput = GenericOrderByInput;
  export type SourceMappingSelect = GenericSelect;
  export type SourceMappingCreateInput = GenericInput;
  export type SourceMappingUpdateInput = GenericInput;
  export const ModelName = {
    User: "User",
    Account: "Account",
    Session: "Session",
    VerificationToken: "VerificationToken",
    Organization: "Organization",
    OrganizationMembership: "OrganizationMembership",
    OrganizationInvitation: "OrganizationInvitation",
    Campaign: "Campaign",
    CampaignMembership: "CampaignMembership",
    CampaignInvitation: "CampaignInvitation",
    Creator: "Creator",
    CreatorPlatformAccount: "CreatorPlatformAccount",
    CreatorMetricsSnapshot: "CreatorMetricsSnapshot",
    CampaignCreator: "CampaignCreator",
    CampaignCreatorDeal: "CampaignCreatorDeal",
    Video: "Video",
    VideoReview: "VideoReview",
    VideoMetricsSnapshot: "VideoMetricsSnapshot",
    OrganizationTwilioConfig: "OrganizationTwilioConfig",
    OrganizationTikTokAccount: "OrganizationTikTokAccount",
    CreatorContactPoint: "CreatorContactPoint",
    SparkCodeRequest: "SparkCodeRequest",
    CreatorMessageThread: "CreatorMessageThread",
    CreatorMessageEvent: "CreatorMessageEvent",
    SparkAuthorization: "SparkAuthorization",
    TikTokPaidMetricSnapshot: "TikTokPaidMetricSnapshot",
    TikTokAdPreviewUrl: "TikTokAdPreviewUrl",
    Note: "Note",
    Tag: "Tag",
    CreatorTag: "CreatorTag",
    Payout: "Payout",
    Activity: "Activity",
    ExternalSyncJob: "ExternalSyncJob",
    SourceMapping: "SourceMapping",
  } as const;
}
